# Generated by Django 4.2.6 on 2023-11-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Фильм', 'Фильм'), ('Сериал', 'Сериал'), ('Мультфильм', 'Мультфильм')], max_length=10, verbose_name='Тип (Фильм, Сериал, Мультфильм)')),
                ('Name_of_film', models.CharField(max_length=50, verbose_name='Название')),
                ('Image_of_film', models.ImageField(blank=True, null=True, upload_to='image/%Y-%m-%d/', verbose_name='Картинка')),
                ('Image_name_of_film', models.ImageField(blank=True, null=True, upload_to='image_name/%Y-%m-%d/', verbose_name='Картинка названия')),
                ('Trailer_of_film', models.FileField(upload_to='trailers/%Y-%m-%d/', verbose_name='Трейлер')),
                ('Video_of_film', models.FileField(upload_to='video/%Y-%m-%d/', verbose_name='Видео')),
                ('Category', models.CharField(max_length=25, verbose_name='Категория')),
                ('Director', models.CharField(max_length=25, verbose_name='Режиссер')),
                ('Time', models.CharField(max_length=25, verbose_name='Продолжительность (часы и минуты)')),
                ('Year', models.CharField(max_length=25, verbose_name='Год выпуска')),
                ('Actors', models.TextField(verbose_name='Актеры')),
                ('Description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
